<a href="https://colab.research.google.com/github/amshanaa/deep-learning-challenge/blob/main/AlphabetSoup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow import keras

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE

new_df = application_df.drop(columns=['EIN','NAME'])

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE

new_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE

var = new_df['APPLICATION_TYPE'].value_counts()
var

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

application_types_to_replace = var[(var<=157)].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE

var1 = new_df['CLASSIFICATION'].value_counts()
var1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

var1[(var1>1)]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

classifications_to_replace = var1[(var1<1800)].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

changes = pd.get_dummies(new_df)
changes.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE

X = changes.drop(columns='IS_SUCCESSFUL').values
y = changes['IS_SUCCESSFUL'].values


# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = X_train_scaled.shape[1]


hidden_node1 = 80
hidden_node2 = 30
hidden_node3 = 1


nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=hidden_node1, activation='relu', input_dim=input_features))

# Second hidden layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=hidden_node2, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE

nn.add(tf.keras.layers.Dense(units=hidden_node3, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                9360

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 11821 (46.18 KB)
Trainable params: 11821 (46.18 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
#  YOUR CODE GOES HERE

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
#  YOUR CODE GOES HERE

fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.5731 - accuracy: 0.7212
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5526 - accuracy: 0.7306
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5488 - accuracy: 0.7307
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7324
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7320
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7332
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7334
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7318
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7343
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7349
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7353
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7356
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7354
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7365
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7371
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7371
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7370
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7385
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7379
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7387
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7373
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7381
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7386
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7387
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7383
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7385
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7394
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7399
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7392
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7393
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7400
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7399
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7397
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7400
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7381
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7399
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7403
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7400
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7405
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7404
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7413
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7400
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7408
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7414
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7421
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7409
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7415
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7426
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7414
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7415
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5305 - accuracy: 0.7422
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7429
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7410
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7426
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7397
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5304 - accuracy: 0.7419
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7418
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7408
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7423
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7425
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5297 - accuracy: 0.7425
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5300 - accuracy: 0.7411
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5295 - accuracy: 0.7421
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5296 - accuracy: 0.7427
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5298 - accuracy: 0.7418
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5298 - accuracy: 0.7422
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5295 - accuracy: 0.7424
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5292 - accuracy: 0.7423
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5295 - accuracy: 0.7417
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7420
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7423
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5292 - accuracy: 0.7423
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7421
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7424
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7421
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5289 - accuracy: 0.7422
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5287 - accuracy: 0.7420
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7426
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7426
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7430
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5284 - accuracy: 0.7421
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7422
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5285 - accuracy: 0.7427
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5281 - accuracy: 0.7425
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5282 - accuracy: 0.7409
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5283 - accuracy: 0.7431
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5282 - accuracy: 0.7434
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7424
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5276 - accuracy: 0.7424
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5282 - accuracy: 0.7427
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7427
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7425
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7423
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5279 - accuracy: 0.7426
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7428
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5276 - accuracy: 0.7427
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5275 - accuracy: 0.7427

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5640 - accuracy: 0.7314 - 321ms/epoch - 1ms/step
Loss: 0.5639894604682922, Accuracy: 0.7314285635948181

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from tensorflow.keras import Model

In [ ]:
model.save('/content/drive/MyDrive/Colab Notebooks/Alphabet Model/model1' , save_format="h5")

NameError: ignored

In [ ]:
filepath = r"C:\Users\amsha\Desktop\BootCamp\Module 21-Challenge\Model Save\AlphabetSoupCharity.h5"
nn.save(filepath, save_format='h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(